stages:
  get_data:
    cmd: python src/get_data.py data/project-74-at-2024-11-06-02-57-deb5fc82.json
    deps:
    - src/get_data.py
    - data/project-74-at-2024-11-06-02-57-deb5fc82.json
    params:
    - data.annotation_path
    - data.output_path
    outs:
    - data/images
    - data/labels
  prepare:
    cmd: python src/prepare.py data/train data/val data/data.yaml
    deps:
    - src/prepare.py
    - data/images
    - data/labels
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/train
    - data/val
    - data/data.yaml
  train:
    cmd: python src/train.py data/train data/val data/data.yaml Safety_Crane_YOLOv11-pose
    deps:
    - data/train
    - data/val
    - data/data.yaml
    - src/train.py
    params:
    - train.mlflow
    - train.seed
    - train.yolo
    outs:
    - Safety_Crane_YOLOv11-pose
