data:
  annotation_path: "./data/project-74-at-2024-11-06-02-57-deb5fc82.json"
  output_path: "data"

prepare:
  split: 0.9
  seed: 42

train:
  seed: 42
  mlflow:
    MLFLOW_TRACKING_URI: "https://mlflow.connectedtech.co.th"
    AWS_ACCESS_KEY_ID: 08rI2JgLEXYi3ctLLfXY
    AWS_SECRET_ACCESS_KEY: YiArLasbrIRBEEmtMocy6PgdGC6G5U4cOKfqJt4R
    MLFLOW_S3_ENDPOINT_URL: "https://minio.connectedtech.co.th/"
  yolo:
    pretrained_model: "yolo11x-pose.pt"
    epochs: 100
    batch_size: 8
    img_size: 640
    device: 0
    project: "Safety_Crane_YOLOv11-pose"
    name: exp4-close_mosaic-100epchs-split0.9




